### ISSUE TITLE
Research how to deploy on AWS the Amarradero Llanero app

### ISSUE THREAD

**Issue by danilonunezgil** [BPMN-sw-evol/AmarraderoLlanero#12]

**Comment by danilonunezgil** [comment]
Register on AWS and try to deploy.

**Comment by jhonalexander019** [comment]
AmarraderoLlanero deployment on AWS completed
**Camunda: http://34.238.155.83:8080/
Database: http://34.238.155.83/dbconexion 
REST endpoint (camunda platform):  http://34.238.155.83:8080/engine-rest**
